### PR TITLE
Fixing typescript typecheck errors.

### PR DESCRIPTION
**Pull request by FrankKleiton**
I was having trouble to build the code due to the request query params of express.

Screenshot_2020-10-25 Screenshot_2020-10-25_13-42-52 png (PNG Image, 1366 × 768 pixels) - Scaled (83%)

I was just trying to run the code to began to study it so I did the simplest thing that  i could throught, with the tiny amount of  typescript knowledge that i have, to get the code running that was add a comparison to check if the params really are a string. Maybe this isn't the optimal thing to do, but as I said I kind learning typescript yet, I am very excited to read your code and learn from it.

### CODE REVIEW

**Review by rcmsoftwaredevelopment — APPROVED** [review]

**Review by rcmsoftwaredevelopment — APPROVED** [review]

**Comment by janishar** [comment]
@FrankKleiton This is not reproducing at my end. 
Can you help me with:
1. What typescript version you are using?
2. Are building the project using `npm run build`?

**Comment by janishar** [comment]
I reproduced it. Let me check

**Comment by FrankKleiton** [comment]
> @FrankKleiton This is not reproducing at my end.
> Can you help me with:
> 
> 1. What typescript version you are using?
> 2. Are you building the project using `npm run build`?

My typescript version is the 4.0.3.

**Comment by FrankKleiton** [comment]
> I reproduced it. Let me check

Okay. Great architecture by the way, I'm enjoying reading yours code very much.

**Comment by janishar** [comment]
@FrankKleiton Really good to know 😄

**Comment by janishar** [comment]
@FrankKleiton Please check the PR #18 
It has been solved though explicit cast to string. 
The cast is safe since this query is validated before being used.

Adding type check though `typeof` is not recommended since we are already using typescript for it.

**Pull request closed without merging**
